services:

  postgres:
    image: debezium/postgres:16
    container_name: alimentador_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app123
      POSTGRES_DB: teste_pacientes
      POSTGRES_INITDB_ARGS: "-c timezone=UTC"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d teste_pacientes"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alimentador_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: alimentador_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - alimentador_net
    profiles:
      - debug

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: alimentador_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - alimentador_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: alimentador_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "alimentador_zookeeper:2181"

      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://alimentador_kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    ports:
      - "9092:9092"
    networks:
      - alimentador_net

  connect:
    image: debezium/connect:2.7.0.Final
    container_name: alimentador_connect
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: alimentador_kafka:29092

      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    networks:
      - alimentador_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "oltp-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "alimentador_kafka:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "alimentador_zookeeper:2181"
    networks:
      - alimentador_net
    restart: unless-stopped

  consumer_universal:
    build:
      context: ./consumers/raw
    container_name: consumer_universal
    depends_on:
      - kafka
    env_file:
      - .env
    environment:
      KAFKA_BROKER: alimentador_kafka:29092
      S3_BUCKET: gbrj-simulator-oltp-datalake
      S3_BASE_PREFIX: raw
    networks:
      - alimentador_net
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local

networks:
  alimentador_net:
    driver: bridge
